### PR TITLE
Fix #1376 -- Require password when user updates email

### LINKED ISSUE #1376: No password verification when changing account's mail address
### Steps to reproduce the error

1. Go to Edit Profile
2. Change mail address

### Actual behavior

User is not prompted to verify their password to confirm identity. 

All the other fixes described in bug #1140 are properly included though: 
1. Confirmation mail to new email address does not include username
2. The mail address is not actually updated until the verification link is clicked
3. Correct notification is sent to the old address

But I wonder if we should ask for password verification as well, as we do when changing the password for instance. 

### Expected behavior

Ask for password verification?

@amplifi, what do you think?

### PR DESCRIPTION
**Pull request by oliverroick**
### Proposed changes in this pull request

- Fixes #1376: Users are now required to enter their passwords if they want to change their email addresses. 
- Adds a new form field `password` to `accounts.forms.ProfileForm`. The field is not required by default; it becomes required when the email is about to change. 
- The corresponding field is also added to `cadasta/templates/accounts/profile.html`. It is hidden by default unless the form is returned with an error; for example when the password did not match.
- Adds `cadasta/core/static/js/profile.js` which takes care of showing and hiding the password field when the email value of the email field has changed. 

I went for the simple UI possible, @clash99 could you have a look if it's ok that way?

### When should this PR be merged

- In time for the next release as this is a high-priority bug fix.

### Risks

Nope.

### Follow-up actions

Nope.

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [ ] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
- [ ] **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [ ] **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Security

- [ ] **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
- [ ] **Are all UI and API inputs run through forms or serializers?** 
- [ ] **Are all external inputs validated and sanitized appropriately?**
- [ ] **Does all branching logic have a default case?**
- [ ] **Does this solution handle outliers and edge cases gracefully?**
- [ ] **Are all external communications secured and restricted to SSL?**

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

File: cadasta/core/static/js/profile.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+$('input#id_email').change(function() {
```
Comment (clash99) [inline cadasta/core/static/js/profile.js]: What do you think about using mouseout instead of change? Reason being that with change, if you update the field and then select the submit button, you may not notice the new field until after the submit & error.  With mouseout, it will add the password field immediately below the email field.

Comment (bjohare) [inline cadasta/core/static/js/profile.js]: @clash99 mouseout won't work if the user tabs to the next field.

**Comment by oliverroick** [comment]
I think Brian's suggestion makes sense. It would make the whole implementation less complex, I can get rid of the JS and the logic to work out whether the password is needed or not. 

I'll wait for comments on this. If I don't hear anything, I'll make the changes later today.

**Comment by amplifi** [comment]
I'd go with @bjohare's and @seav's suggestions; username and/or password changes both require authentication, and the field is always visible but enables when changing those fields.

**Comment by clash99** [comment]
Sounds good - I'm just wondering if we throw a password field on that page where you update the username and email, it would also seem that is where password changes are made as well.  Seems a prompt to enter the password is more common.

**Comment by clash99** [comment]
Another thought - what about something like this that sets the password field apart a bit so that it doesn't seem like another update field?  

screenshot 2017-04-07 07 56 04

**Comment by oliverroick** [comment]
I'll do as @clash99 suggested. I'll also make the password generally required. That way user's funny colleague can't change the Full Name to Dude McDudeface or so.

**Comment by oliverroick** [comment]
I've made the password required for all updates now. Here's what it should look like now:

screen shot 2017-04-07 at 15 54 37
