### PR TITLE
Fix #662 -- Define MIMETYPE_LOOKUP to detect type from file extension

### LINKED ISSUE #662: Improve browser detection of .gpx files on GPX import
### The problem

Currently, browser mime-type detection of files with `.gpx` extension is unreliable. GPX files that need to be imported into the platform must be renamed to have a `.xml` extension. We should investigage how to improve correct mime-type detection of `.gpx` files and/or improve _django-buckets_ error reporting if this is not possible.
### Actual behavior

GPX files to be imported must be renamed to have a `.xml` extension. Error messaging if the user attempts to upload a `.gpx` file is not detailed enough.
### Expected behavior

Ideally we would be able to import `.gpx` files directly. Failing that, the error reporting should be improved.

### LINKED ISSUE #972: Files are deleted from S3 before a model instance is saved
### Steps to reproduce the error

1. Create a resource or upload an XLSForm to a project and save.
2. Edit the resource or project and click "remove" next to the file field. 
3. Cancel editing. 
4. Try to access the file on S3.

### Actual behavior

The file is deleted from S3, whether the model instance is saved or not. If the user removes the file from the field and then cancels editing, the database will still have the link but the resource does not exist. 

### Expected behavior

The file should only be deleted when the model instance is actually saved. That means removing the file from S3 should be moved from django-buckets into the respective model. Before saving we need to check whether the file was removed and then delete the file from S3. If the file was replace with a new file, the old file should be removed. 

Currently, this affects the following models (probably not exhaustive):

- `Project` (for XLSForms)
- `Resource`

### PR DESCRIPTION
**Pull request by oliverroick**
### Proposed changes in this pull request

- Fixes #662
- Fixes #972 (The fix comes with the new django-buckets version, I did not chnage any code in the platform. When reviewing, it should be tested if uploading and deleting files work as expected)
- Bump django-buckets to 0.1.19a5, which is a pre-release version. I suggest to check this PR, and when it's accepted, I will make a full release and update the requirements before merging. 
- Rename `MIME_LOOKUPS` to `ICON_LOOKUPS` to make it more obvious what the `dict` is for (looking up icons for mime types).
- Introduces a new `MIME_LOOKUPS` `dict` to lookup mime types for file extensions that are otherwise not detected in the browser.
- Change `file-upload.js` to use either the mime type detected by the browser or the one defined in `MIME_LOOKUPS`.

### When should this PR be merged

Soon, as #972 is a high priority bug.

### Risks

None foreseen.

### Follow up actions

Before merging the PR, we should make a release of django-buckets and update the requirements. 

#### General

- [x] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [x] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts. 

#### Functionality

- [x] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [x] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [x] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [x] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [x] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [x] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [x] **If this is a bug fix, are tests for the issue in place**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.

#### Documentation

- [x] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [x] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [x] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

File: cadasta/core/static/js/file-upload.js [hunk 1]
```diff
@@ -16,7 +16,10 @@ $(function() {
 
     $('input[name="original_file"]').val(file.name);
     $('input[name="details-original_file"]').val(file.name);
-    $('input[name="mime_type"]').val(file.type);
+
+    var ext = file.name.split('.').slice(-1)[0];
+    var type = file.type || MIME_LOOKUPS[ext];
```
Comment (seav) [inline cadasta/core/static/js/file-upload.js]: `MIME_LOOKUPS` does not point to any existing JavaScript array. I get the following in the JavaScript console:
```
MIME_LOOKUPS is not defined
```

Comment (oliverroick) [inline cadasta/core/static/js/file-upload.js]: On which page?

Comment (seav) [inline cadasta/core/static/js/file-upload.js]: On the resources upload page: /organizations/<org>/projects/<project>/resources/add/new/

Comment (seav) [inline cadasta/core/static/js/file-upload.js]: Ah. Wait. I haven't upgraded django-buckets yet.

Comment (seav) [inline cadasta/core/static/js/file-upload.js]: OK. Now it works. Sorry for the false alarm.

**Comment by seav** [comment]
**Checklist: "Are all necessary strings marked for translation?"**
How should we handle such strings in django-buckets? There's "File type not allowed.", "Uploading...", and "(Remove)" for starters.

**Comment by seav** [comment]
When I replace a file with another one, the original file is still uploaded (at least on the dev VM with the FakeS3Storage).

**Comment by seav** [comment]
And there's a side effect. If I do the following steps:

1. Create a resource and save.
2. Edit the resource and click "Remove" next to the file field.
3. Select another file and wait for it to upload.
4. Click "Remove" next to the file field.
5. Select a third file and wait for it to upload.
6. Save.

The file uploaded at step 3 is not deleted and is still accessible from S3.

**Comment by oliverroick** [comment]
Both are valid issues, but I don't know how to address them. 

The idea of django-buckets is that you upload the file to S3 before you save the form, so only the URL needs to be stored. Currently, when you click "remove" the file is always deleted from S3, even if the model itself is not saved, which led to an issue where you click "remove" but don't save the form resulting in a URL pointing nowhere. 

This PR addresses that: The file is only removed from S3 when the model's value has changed. So the replacement of a file with a new file removes the old file from S3. Same when you leave the field blank. 

So in the cases you describe above, the file is always uploaded but never removed, because it is replaced before the model is saved. In other words, the backend doesn't know that there is a file that needs to be removed. 

The only possible solution I can think of is to keep a list of all files that need removing and send it with the form. But I would have to implement tasks that should be handled by django-buckets (deleting all the files) in the platform code.

**Comment by oliverroick** [comment]
For translations, this is something I can address on the django-buckets side but that's a separate issue.

**Comment by seav** [comment]
I agree that this is tricky to solve this issue such that we don't prematurely delete files nor do we store files unnecessarily in S3. The current behavior where files are deleted prematurely (#972) is definitely not good so it would be better to err on the side of keeping files in S3 even if they are no longer needed, which this PR does address.

But while I don't expect the side-effect mentioned in [this comment](https://github.com/Cadasta/cadasta-platform/pull/1010#issuecomment-267956205) to be easily solved, I do expect that when the resource or project is finally saved, that the old file is deleted from S3. If I understand it correctly, the code to do just that is not yet included in this PR?

**Comment by oliverroick** [comment]
> I do expect that when the resource or project is finally saved, that the old file is deleted from S3. If I understand it correctly, the code to do just that is not yet included in this PR?

Yes, the file should be deleted, does it not work?

**Comment by seav** [comment]
Nope, the file is not deleted. But I did add a caveat: "at least on the dev VM with the FakeS3Storage"

**Comment by oliverroick** [comment]
Added an update to django-buckets, the file should now be deleted when it's replaced.

**Comment by seav** [comment]
OK. The original file is now being deleted. I am approving this pull request (so only @bjohare's review is needed). But we have 2 further issues:

1. The mentioned side effect needs to be resolved in the future, whether this involves adding more sophisticated platform code so no uploaded files are left behind in the first place, or a management command or scheduled job to clean up stray files in S3 from time to time.
2. The untranslatable strings still need to be made translatable.

**Comment by oliverroick** [comment]
@bjohare Changed the message text as requested

**Comment by oliverroick** [comment]
Django-buckets 0.1.19 is released and added to the requirements with this PR. This is ready to go.
